const languages = {
  en: {
    login: 'Login',
    loginTitle: 'Porttitor nunc duis ultrices consectetur cursus non et.',
    phoneNumber: 'Phone Number',
    mobileNumber: 'Mobile Number',
    password: 'Password',
    forgetPassword: 'Forget Password?',
    signIn: 'Sign in',
    dontHaveAcc: 'Dont have an account?',
    register: 'Register',
    helloAgain: 'Hello Again',
    welcomeBack: 'Welcome back you ve been missed!',
    labelEmail: 'Email address or phone',
    labelPassword: 'Password',
    or: 'Or',
    notMember: 'Not a member?',
    createAccount: 'Create an account',
    skip: 'Skip',
    fullName: 'Full Name',
    email: 'Email',
    city: 'City',
    haveAccount:'Have Account',
    invalideEmail:'Invalid email',
    required:'Required',
    passwordShort:'Password is too short - should be 8 chars minimum.',
    phoneError:'Phone number is not valid'
  },
  ar: {
    login: 'تسجيل الدخول',
    helloAgain: 'مرحبا مجددا',
    welcomeBack: 'مرحبا بعودتك لقد فقدناك!',
    labelEmail: 'عنوان البريد الالكتروني او الهاتف',
    labelPassword: 'كلمه المرور',
    forgetPassword: 'نسيت كلمه المرور ؟',
    or: 'أو',
    notMember: 'لست عضوا',
    createAccount: 'انشاء حساب',
    skip: 'تخطي',
    register: 'عمل حساب جديد',
    fullName: 'الاسم الكامل',
    email: 'البريد الالكتروني',
    city: 'المدينه',
    phoneNumber: 'رقم الموبايل',
    password: 'كلمه المرور',
    haveAccount:'هل لديك حساب',
    invalideEmail:'الاميل مطلوب',
    required:'مطلوب',
    passwordShort:'كلمه المرور صغيره - يجب ان لا تقل عن 8 احرف',
    phoneError:'رقم الموبايل غير صحيح'
  },
};
export default languages;
