const languages: any = {
  en: {
    login: 'Login',
    loginTitle: 'Porttitor nunc duis ultrices consectetur cursus non et.',
    phoneNumber: 'Phone Number',
    mobileNumber: 'Mobile Number',
    password: 'Password',
    forgetPassword: 'Forget Password?',
    signIn: 'Sign in',
    dontHaveAcc: 'Dont have an account?',
    register: 'Register',
    helloAgain: 'Hello Again',
    welcomeBack: 'Welcome back you ve been missed!',
    labelEmail: 'Email address or phone',
    labelPassword: 'Password',
    or: 'OR',
    notMember: 'Not a member?',
    createAccount: 'Create an account',
    skip: 'Skip',
    fullName: 'Full Name',
    email: 'Email',
    city: 'City',
    haveAccount: 'Have Account',
    invalideEmail: 'Invalid email',
    required: 'Required',
    passwordShort: 'Password is too short - should be 8 chars minimum.',
    phoneError: 'Phone number is not valid',
    explore: 'Explore',
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
    meditation: 'Meditation',
    enjoy: 'Enjoy',
    welcomeBackHome: 'Welcome Back',
    user: 'Mariem Mohamed Sayed ',
    searchInApp: 'Search in app',
    types: 'Category',
    trips: 'Trips',
    aquaPark: 'Aqua park',
    nileTrip: 'Nile Trip',
    surfing: 'Surfing',
    bBuggy: 'B-Buggy',
    diving: 'Diving',
    experiences: 'Experiences',
    seeMore: 'See More',
    cardTitle: 'Nigth Comping Trip',
    cardDescription:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    cardLocation: 'Sharm el-Sheikh downtown at the dean',
    cardName: 'Jamp',
    cardStars: '3.4',
    main: 'Home',
    exploreN: 'Explore',
    notification: 'Notification',
    profile: 'Profile',
    divingActivity: 'Diving Activity',
    hestegal: 'Hastagel Agency',
    description: 'Description',
    LE: '500 L.E',
    lorem:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    bookNow: 'Book Now',
    selectCountry: 'Select a country',
    addressConfirmation: 'Address Confirmation',
    yourLocation: 'Your Location',
    enterYourPlace: 'Enter your place',
    date: 'Date',
    time: 'Time',
    numberOfPerson: 'Number Of Person',
    termCondition: 'Terms & Conditions',
    bookingDetails: 'Booking Details',
    calendar: 'Calendar',
    category: 'Category',
    rating: 'Rating',
    filter: 'Filter',
    reset: 'Reset',
    applyFilter: 'Apply Filter',
    rangePrice: 'Range Price',
    le: 'L.E',
    providerProfile: 'Provider Profile',
    review: 'Review',
    sharm: 'Sharm El-Shaikh',
    about: 'About',
    experience: 'Activities',
    mohamed: 'Mohamed Ahmed',
    editProfile: 'Edit Profile',
    myBooking: 'My bookings',
    wishlist: 'Wishlist',
    logout: 'Logout',
    contactUs: 'Contact Us',
    address: 'Address',
    faq: 'FAQ',
    sendUs: 'Send Us',
    callUs: 'Call Us',
    fullAddress: 'Sharm El-Sheikh Al-Qwaisi Street, Khan Al-Khalil',
    phone: '+20126444515',
    Email: 'timeout-app@gmail.com',
    reservationRejected:
      'Your reservation is rejected because the trip complete',
    Date: '12-5-2021 3:00 PM',
    reservationAccepted: 'Your reservation is accepted confirm the payment',
    tripConfirmed: 'Trip Payment has been confirmed',
    addActivity: 'We add new activity',
    notHaveInbox: 'Empty',
    paymentCode: 'Payment Code',
    youCan: 'You can pay by Number',
    note: 'Note : The code is available for 24 hours only to confirm payment',
    confirm: 'Confirm',
    cancel: 'Cancel',
    allowNotification: 'Allow notification to be delivered to you',
    allow: 'Allow',
    details: 'Details',
    flightConfirmed: 'The flight reservation has been confirmed',
    settings: 'Settings',
    language: 'Language',
    currency: 'Currency',
    changePassword: 'Change Password',
    helpCenter: 'Help Center',
    allowN: 'Allow Notification',
    darkMode: 'Dark Mode',
    arabic: 'Arabic',
    english: 'English',
    changeYourPassword: 'Change Your Password',
    oldPassword: 'Old Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    myBookings: 'My Bookings',
    currentBooking: 'Current Bookings',
    lastBooking: 'Last Bookings',
    drivingActivity: 'Driving Activity',
    numOfPerson: '2 Member',
    onlyDate: '12-5-2021',
    payment: 'Payment',
    fawry: 'Fawry',
    price: 'Price',
    others: 'Others',
    paidBy: 'Paid by',
    total: 'Total',
    wait: 'Waiting',
    rejected: 'Rejected',
    agree: 'Agree',
    lastBookingTitle: 'Driving Activity By Hastahe Company',
    countryCode: 'Country Code',
    saveEditing: 'Save Editing',
    inbox: 'Inbox',
    locationAccess: 'Allow access to your current location',
    pleaseEnterYourEmail: 'Please enter your email',
    requestReceive:'We will confirm your booking within 24 hours see more check your email',
    activity:'Activity',
  },
  ar: {
    login: 'تسجيل الدخول',
    helloAgain: 'مرحبا مجددا',
    welcomeBack: 'مرحبا بعودتك',
    labelEmail: 'عنوان البريد الالكتروني او الهاتف',
    labelPassword: 'كلمه المرور',
    forgetPassword: 'نسيت كلمه المرور ؟',
    or: 'أو',
    notMember: 'لست عضوا؟',
    createAccount: 'انشاء حساب',
    skip: 'تخطي',
    register: 'إنشاء حساب جديد',
    fullName: 'الاسم الكامل',
    email: 'البريد الالكتروني',
    city: 'المدينه',
    phoneNumber: 'رقم الموبايل',
    password: 'كلمه المرور',
    haveAccount: 'هل لديك حساب؟',
    invalideEmail: 'الاميل مطلوب',
    required: 'مطلوب',
    passwordShort: 'كلمه المرور صغيره - يجب ان لا تقل عن 8 احرف',
    phoneError: 'رقم الموبايل غير صحيح',
    explore: 'يستكشف',
    desc: 'هذا النص مثال لنص يمكن ان يستبدل في نفس المساحه،لقد تم توليد هذا النص من مولد النص العربي',
    meditation: 'تأمل',
    enjoy: 'استمتع',
    welcomeBackHome: 'مرحبا بعودتك',
    user: 'مريم محمد سيد',
    searchInApp: 'ابحث في التطبيق',
    types: 'اقسام',
    trips: 'رحلات',
    aquaPark: 'حديقة مائية',
    nileTrip: 'رحلة النيل',
    surfing: 'تصفح',
    bBuggy: 'بيتش باج',
    diving: 'الغطس',
    experiences: 'رحلات',
    seeMore: 'شاهد المزيد',
    cardTitle: 'رحلة ليلية',
    cardDescription:
      'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى',
    cardLocation: 'وسط البلد بشرم الشيخ عند العميد',
    cardName: 'Jamp',
    cardStars: '3.4',
    main: 'الرئيسية',
    exploreN: 'استكشاف',
    notification: 'تنبيهات',
    profile: 'الملف الشخصي',
    divingActivity: 'نشاط الغوص',
    hestegal: 'Hastagel Agency',
    description: 'الوصف',
    LE: '500 جنية',
    lorem:
      'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى',
    bookNow: 'احجز الآن',
    selectCountry: 'اختر دولة',
    addressConfirmation: 'تأكيد العنوان',
    yourLocation: 'موقعك الحالى',
    enterYourPlace: 'أدخل مكانك',
    date: 'التاريخ',
    time: 'الوقت',
    numberOfPerson: 'عضو',
    termCondition: 'البنود و الظروف',
    bookingDetails: 'تفاصيل الحجز',
    calendar: 'التقويم',
    category: 'أنواع الرحلات',
    rating: 'التقيمات',
    filter: 'تصفية النتائج',
    reset: 'إعادة ضبط',
    applyFilter: 'عمل تصفية',
    rangePrice: 'نطاق السعر',
    le: 'جنية',
    providerProfile: 'الملف الشخصى للشركه',
    review: 'اراء العملاء',
    sharm: 'شرم الشيخ',
    about: 'نبذه عننا',
    experience: 'أنشطة',
    mohamed: 'محمد أحمد',
    editProfile: 'تعديل الملف الشخصي',
    myBooking: 'حجوزاتى',
    wishlist: 'القائمه المفضله',
    logout: 'تسجيل خروج',
    contactUs: 'التواصل معانا',
    address: 'العنوان',
    faq: 'الواتس اب',
    sendUs: 'البريد الالكترونى',
    callUs: 'رقم الهاتف',
    fullAddress: 'شارع شرم الشيخ العويسي خان الخليل',
    phone: '+20126444515',
    Email: 'timeout-app@gmail.com',
    reservationRejected: 'حجزك مرفوض لأن اكتملت الرحلة',
    Date: '12-5-2021 3:00 PM',
    reservationAccepted: 'تم قبول حجزك وتأكيده الدفع',
    tripConfirmed: 'تم تأكيد دفع الرحلة',
    addActivity: 'نضيف نشاط جديد',
    notHaveInbox: 'ليس لديك أى رسائل',
    paymentCode: 'الدفع',
    youCan: 'يمكمك الدفع عن طريق الرقم',
    note: 'ملحوظة : الكود متاح لمدة 24 ساعة فقط لتأكيد الدفع',
    confirm: 'تاكيد',
    cancel: 'الالغاء',
    allowNotification: 'السماح بتسليم الإخطارات لك',
    allow: 'السماح',
    details: 'التفاصيل',
    flightConfirmed: 'تم تاكيد الحجز',
    settings: 'الاعدادات',
    language: 'اللغه',
    currency: 'عملة',
    changePassword: 'تغيير كلمة المرور',
    helpCenter: 'التواصل معانا',
    allowN: 'السماح بالتنبيهات',
    darkMode: 'الوضع الليلي',
    arabic: 'عربي',
    english: 'إنجليزي',
    changeYourPassword: 'غير كلمة المرور الخاصة بك',
    oldPassword: 'كلمة المرور القديمة',
    newPassword: 'كلمة مرور جديدة',
    confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
    myBookings: 'حجوزاتى',
    currentBooking: 'الرحله الحالية',
    lastBooking: 'الرحلات السابقة',
    drivingActivity: 'نشاط الغوص',
    numOfPerson: '2 افراد',
    onlyDate: '12-5-2021',
    payment: 'الدفع',
    fawry: 'فورى',
    price: 'السعر',
    others: 'اخرى',
    paidBy: 'طريقة الدفع',
    total: 'السعر',
    lastBookingTitle: 'نشاط القيادة بواسطة شركة Hastahe',
    wait: 'انتظار',
    rejected: 'الالغاء',
    agree: 'موافقه',
    countryCode: 'كود البلد',
    saveEditing: 'حفظ التعديلات',
    inbox: 'التنبيهات',
    locationAccess: 'السماح بالوصول الي موقعك',
    pleaseEnterYourEmail: 'من فضلك أدخل بريدك الإلكتروني',
    requestReceive:'يرجي الانتظار ٢٤ ساعة لتاكيد طلب الحجز برجاء متابعة بريدك الكتروني او صندوق الاشعارات',
    activity:'انشطه'
  },
};
export default languages;
