export const images = {
  test: require('./testtest.jpeg'),
  logo: require('./logo.png'),
  facebook: require('./facebook.png'),
  instagram: require('./instagram.png'),
  present: require('./present.jpg'),
  branding1: require('./branding_1.png'),
  branding2: require('./branding_2.png'),
  branding3: require('./branding_3.png'),
  splashBg: require('./splashBg.png'),
  downArrow: require('./down-arrow.png'),
  slider1: require('./Slider-1.png'),
  slider2: require('./Slider-2.png'),
  slider3: require('./Slider-3.png'),
  onboardingbg: require('./onboardingbg.png'),
};
